name: Terraform Security Scan

on:
  pull_request:
    branches: [ "main" ]

jobs:
  tfsec:
    name: Run tfsec security checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Run tfsec
        run: tfsec .